__title__ = "bcrp_data"
__version__ = "0.0.0"
__autor__ = "Adrian Vicente Vega"
__email__ = "a.vicentevega31@gmail.com"
__description__ = "Librería de python que te permite descargar data del Banco Central de Reserva del Perú (BCRP)"